// Docker Compose Generator
// Generates docker-compose.yml file for Frigate deployment
// This is separate from config.yml

export interface DockerComposeConfig {
  volumes: {
    config_path: string;
    storage_path: string;
    cache_size?: number;
  };
  ports: {
    web_port: number;
    rtsp_port: number;
    webrtc_tcp_port: number;
    webrtc_udp_port: number;
  };
  devices: string[];
  environment: Record<string, string>;
  shm_size?: string;
  privileged?: boolean;
}

export class DockerComposeGenerator {
  /**
   * Generate docker-compose.yml content
   */
  static generateCompose(config: DockerComposeConfig): string {
    const {
      volumes,
      ports,
      devices,
      environment,
      shm_size = '256mb',
      privileged = true
    } = config;

    const composeConfig = {
      services: {
        frigate: {
          container_name: 'frigate',
          privileged,
          restart: 'unless-stopped',
          stop_grace_period: '30s',
          image: 'ghcr.io/blakeblackshear/frigate:stable',
          shm_size,
          devices: devices.length > 0 ? devices : undefined,
          volumes: [
            '/etc/localtime:/etc/localtime:ro',
            `${volumes.config_path}:/config`,
            `${volumes.storage_path}:/media/frigate`,
            {
              type: 'tmpfs',
              target: '/tmp/cache',
              tmpfs: {
                size: volumes.cache_size || 1000000000
              }
            }
          ],
          ports: [
            `${ports.web_port}:8971`,
            `${ports.rtsp_port}:8554`,
            `${ports.webrtc_tcp_port}:8555/tcp`,
            `${ports.webrtc_udp_port}:8555/udp`
          ],
          environment: Object.keys(environment).length > 0 ? environment : undefined
        }
      }
    };

    return this.toYAML(composeConfig);
  }

  /**
   * Convert config object to YAML string
   */
  private static toYAML(obj: any, indent: number = 0): string {
    const spaces = '  '.repeat(indent);
    let yaml = '';

    for (const [key, value] of Object.entries(obj)) {
      // Skip null, undefined
      if (value === null || value === undefined) {
        continue;
      }

      // Skip empty objects
      if (typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === 0) {
        continue;
      }

      if (typeof value === 'object' && !Array.isArray(value)) {
        // Object - recurse
        const childYaml = this.toYAML(value, indent + 1);
        if (childYaml.trim()) {
          yaml += `${spaces}${key}:\n`;
          yaml += childYaml;
        }
      } else if (Array.isArray(value)) {
        // Skip empty arrays
        if (value.length === 0) {
          continue;
        }
        yaml += `${spaces}${key}:\n`;
        value.forEach((item) => {
          if (typeof item === 'object' && item !== null) {
            // Check if it's a volume object with type
            if (item.type === 'tmpfs') {
              yaml += `${spaces}  - type: ${item.type}\n`;
              yaml += `${spaces}    target: ${item.target}\n`;
              if (item.tmpfs) {
                yaml += `${spaces}    tmpfs:\n`;
                yaml += `${spaces}      size: ${item.tmpfs.size}\n`;
              }
            } else {
              // Other objects - inline format
              yaml += `${spaces}  - `;
              const itemEntries = Object.entries(item);
              if (itemEntries.length > 0) {
                const [firstKey, firstValue] = itemEntries[0];
                yaml += `${firstKey}: ${firstValue}\n`;
                for (let i = 1; i < itemEntries.length; i++) {
                  const [k, v] = itemEntries[i];
                  yaml += `${spaces}    ${k}: ${v}\n`;
                }
              }
            }
          } else {
            yaml += `${spaces}  - ${item}\n`;
          }
        });
      } else if (typeof value === 'string') {
        // Quote strings with special characters
        const needsQuotes = /[:#@]/.test(value) || value.includes(' ');
        yaml += `${spaces}${key}: ${needsQuotes ? `"${value}"` : value}\n`;
      } else if (typeof value === 'boolean') {
        yaml += `${spaces}${key}: ${value}\n`;
      } else {
        yaml += `${spaces}${key}: ${value}\n`;
      }
    }

    return yaml;
  }

  /**
   * Get default docker-compose.yml template
   */
  static getDefaultCompose(): string {
    return `# Docker Compose configuration for Frigate
# Generated by Frigate Configuration Tool

services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb"
    devices:
      # Uncomment for Coral USB
      # - /dev/bus/usb:/dev/bus/usb
      # Uncomment for Intel GPU
      # - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"  # Web UI
      - "8554:8554"  # RTSP
      - "8555:8555/tcp"  # WebRTC
      - "8555:8555/udp"  # WebRTC
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
`;
  }

  /**
   * Get recommended devices based on hardware
   * Updated for Frigate 2025: NVIDIA uses runtime, Hailo needs device mapping
   */
  static getRecommendedDevices(hardwareType: string): string[] {
    switch (hardwareType) {
      case 'coral':
      case 'edgetpu':
        return ['/dev/bus/usb:/dev/bus/usb', '/dev/apex_0:/dev/apex_0'];
      case 'intel':
      case 'qsv':
      case 'vaapi':
        return ['/dev/dri/renderD128:/dev/dri/renderD128'];
      case 'nvidia':
      case 'cuda':
      case 'onnx':  // ONNX detector for NVIDIA
        // NVIDIA doesn't use --device mapping, uses nvidia runtime or deploy.resources
        return [];
      case 'hailo':
      case 'hailo8':
      case 'hailo8l':
        // Hailo needs device mapping
        return ['/dev/hailo0:/dev/hailo0'];
      default:
        return [];
    }
  }
}
